### ISSUE TITLE
Resources shouldn't end on a slash

### ISSUE THREAD

**Issue by DanMan** [maxpoulin64/protondb-api#2]
Minor issue, but it should really be:

    /games
    /games/<appId>/reports

because those are the resource names. With the slash added, they become paths.

**Comment by maxpoulin64** [comment]
I personally like the ending slash because I've by experience had cases where `/thing` and `/thing/` had slightly different functions, statistics and list of things respectively. I'll have to agree it's probably better to stick with conventions there.

Made both acceptable to remain compatible for, the path versions will go the next time I overhaul the router when I've settled on how I want to implement routing properly.
